name: Update Visitor Data and Deploy

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch: # Allows manual triggering

permissions:
  contents: write # Allow write access to the repository

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Or your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Update Visitor Data
        run: npm run update-visitors-7d

      - name: Build Project
        run: npm run build

      - name: Deploy to DreamHost
        run: npm run deploy
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}